// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3DqQloffT5U69N-zjWV87EKNdmIYv3U',
    appId: '1:246547705306:web:7d35b3b419e326142124e3',
    messagingSenderId: '246547705306',
    projectId: 'activity-14-aae52',
    authDomain: 'activity-14-aae52.firebaseapp.com',
    storageBucket: 'activity-14-aae52.firebasestorage.app',
    measurementId: 'G-ESQMZP77Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3tyklA2NOv4wrtzCtnqvSTSayc5EHUbk',
    appId: '1:246547705306:android:75b21c19fa8a95302124e3',
    messagingSenderId: '246547705306',
    projectId: 'activity-14-aae52',
    storageBucket: 'activity-14-aae52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqI8sgHIg07O3ifh5MwLJNFy6GXVOeSHg',
    appId: '1:246547705306:ios:918afe10c59c60ef2124e3',
    messagingSenderId: '246547705306',
    projectId: 'activity-14-aae52',
    storageBucket: 'activity-14-aae52.firebasestorage.app',
    iosBundleId: 'com.example.activity16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqI8sgHIg07O3ifh5MwLJNFy6GXVOeSHg',
    appId: '1:246547705306:ios:918afe10c59c60ef2124e3',
    messagingSenderId: '246547705306',
    projectId: 'activity-14-aae52',
    storageBucket: 'activity-14-aae52.firebasestorage.app',
    iosBundleId: 'com.example.activity16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb3DqQloffT5U69N-zjWV87EKNdmIYv3U',
    appId: '1:246547705306:web:709af5042494e08e2124e3',
    messagingSenderId: '246547705306',
    projectId: 'activity-14-aae52',
    authDomain: 'activity-14-aae52.firebaseapp.com',
    storageBucket: 'activity-14-aae52.firebasestorage.app',
    measurementId: 'G-R2CLS85C0M',
  );
}
